name: Continuous Integration
on: issue_comment

jobs:
  docker-test:
    name: Docker Test
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        uses: docker://apline:latest
        with:
          entrypoint: /bin/echo
          args: Hello, World!
